version: '3.9'

services: 

    frontend:
        build: './frontend'
        ports: 
            - '3001:3000'
        expose: 
            - '3000'
            - '443'
        volumes: 
            - './frontend/:/var/www/html/'
        depends_on:
            - backend

    backend:
        image: 'node:14.17.4-alpine'
        build: './backend/docker/'
        working_dir: '/home/node/app'
        volumes: 
            - './backend/:/home/node/app'
        expose: 
            - '4431'
            - '3000'
        ports: 
            - '4431:4431'
        command: 'npx nodemon index.js'

    nginx:
        image: 'nginx:1.21.1-alpine'
        ports: 
            - '4432:443'
        expose: 
            - '80'
            - '443'
        build: './nginx/'
        volumes: 
            - './frontend/build/:/usr/share/nginx/html/'
        depends_on: 
            - backend
            - frontend